
// This file has been generated by the GUI designer. Do not modify.
namespace goprogtk
{
	public partial class SettingsWindow
	{
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget goprogtk.SettingsWindow
			this.Name = "goprogtk.SettingsWindow";
			this.Title = global::Mono.Unix.Catalog.GetString ("SettingsWindow");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 400;
			this.DefaultHeight = 300;
			this.Show ();
		}
	}
}
